In [2]:
import pandas as pd

# Base Dataset Penjualan Retail
data = {
    "Nama": ["Andi", "Budi", "Citra", "Dina", "Eko", "Fajar", "Gita", "Hani"],
    "Produk": ["Laptop", "Mouse", "Keyboard", "Laptop", "Mouse", "Headset", "Keyboard", "Laptop"],
    "Kategori": ["Elektronik", "Aksesoris", "Aksesoris", "Elektronik", "Aksesoris", "Aksesoris", "Aksesoris", "Elektronik"],
    "Harga": [7000000, 150000, 300000, 6500000, 175000, 450000, 275000, 7200000],
    "Jumlah": [1, 2, 1, 1, 3, 2, 2, 1],
    "Kota": ["Kuningan", "Cirebon", "Kuningan", "Majalengka", "Cirebon", "Kuningan", "Majalengka", "Cirebon"]
}

df = pd.DataFrame(data)

df['Total'] = df['Jumlah'] * df['Harga']

print("========== TOTAL PENDAPATAN ==========")
print(df[['Produk', 'Harga', 'Jumlah', 'Total']])

print("-"*40)
#mencari total pendapatan berdasarkan kota
total_kota = df.groupby('Kota')['Total'].sum().sort_values(ascending=False)

print("Total Pendapatan Kota: ")
print(total_kota)

print("-"*40)
#rata rata harga kategori
rata_kategori = df.groupby('Kategori')['Harga'].mean().sort_values(ascending = False)
print(rata_kategori)

print("-"*40)
print("Total Pendapatan Keseluruhan:", df['Total'].sum())

========== TOTAL PENDAPATAN ==========
     Produk    Harga  Jumlah    Total
0    Laptop  7000000       1  7000000
1     Mouse   150000       2   300000
2  Keyboard   300000       1   300000
3    Laptop  6500000       1  6500000
4     Mouse   175000       3   525000
5   Headset   450000       2   900000
6  Keyboard   275000       2   550000
7    Laptop  7200000       1  7200000
----------------------------------------
Total Pendapatan Kota:
Kota
Kuningan      8200000
Cirebon       8025000
Majalengka    7050000
Name: Total, dtype: int64
----------------------------------------
Kategori
Elektronik    6900000.0
Aksesoris      270000.0
Name: Harga, dtype: float64
----------------------------------------
Total Pendapatan Keseluruhan: 23275000

In [ ]:
#filtering berdasarkan produk
df_laptop = df[df['Produk'] == "Laptop"]

df_laptop

----------------------------------------

   Nama  Produk    Kategori    Harga  Jumlah        Kota    Total
0  Andi  Laptop  Elektronik  7000000       1    Kuningan  7000000
3  Dina  Laptop  Elektronik  6500000       1  Majalengka  6500000
7  Hani  Laptop  Elektronik  7200000       1     Cirebon  7200000

In [12]:

#filter berdasarkan harga > 5 juta
exvensive_items = df[df['Harga'] > 5000000]

exvensive_items

   Nama  Produk    Kategori    Harga  Jumlah        Kota    Total
0  Andi  Laptop  Elektronik  7000000       1    Kuningan  7000000
3  Dina  Laptop  Elektronik  6500000       1  Majalengka  6500000
7  Hani  Laptop  Elektronik  7200000       1     Cirebon  7200000

In [15]:
#melihat total pendapatan atau jumlah barang yang terjual berdasarkan masing kota

sales_per_kota = df.groupby('Kota')['Jumlah'].sum()
print(sales_per_kota)

Kota
Cirebon       6
Kuningan      4
Majalengka    3
Name: Jumlah, dtype: int64